zabbix_export:
  version: '6.4'
  host_groups:
    - uuid: bc29234bf2f644f390184366d7b0e24a
      name: elk
    - uuid: 70ee90372f8d4c46a5791d316c14a35e
      name: webservers
    - uuid: 6f6799aa69e844b4b3918f779f2abf08
      name: 'Zabbix servers'
  hosts:
    - host: elasticsearch
      name: elasticsearch
      templates:
        - name: 'Linux by Zabbix agent'
      groups:
        - name: elk
      interfaces:
        - useip: 'NO'
          dns: elasticsearch
          interface_ref: if1
      inventory_mode: DISABLED
    - host: kibana
      name: kibana
      templates:
        - name: 'Linux by Zabbix agent'
      groups:
        - name: elk
      interfaces:
        - useip: 'NO'
          dns: kibana
          interface_ref: if1
      inventory_mode: DISABLED
    - host: webserver01
      name: webserver01
      templates:
        - name: 'Nginx by Zabbix agent'
      groups:
        - name: webservers
      interfaces:
        - useip: 'NO'
          dns: webserver01
          interface_ref: if1
      inventory_mode: DISABLED
    - host: webserver02
      name: webserver02
      templates:
        - name: 'Nginx by Zabbix agent'
      groups:
        - name: webservers
      interfaces:
        - useip: 'NO'
          dns: webserver02
          interface_ref: if1
      inventory_mode: DISABLED
    - host: 'Zabbix server'
      name: 'Zabbix server'
      templates:
        - name: 'Linux by Zabbix agent'
        - name: 'Zabbix server health'
      groups:
        - name: 'Zabbix servers'
      interfaces:
        - interface_ref: if1
      inventory:
        name: zabbix
        os: 'Linux version 5.15.0-118-generic (buildd@lcy02-amd64-080) (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for U'
        location_lat: '56.95387'
        location_lon: '24.22067'
      inventory_mode: AUTOMATIC
