---
- name: Install elasticsearch
  hosts: elasticsearch
  become: yes
  roles:
    - elasticsearch

- name: Install Kibana
  hosts: kibana
  become: yes
  roles:
    - kibana

- name: Deploy Filebeat
  hosts: web
  become: yes
  roles:
    - filebeat

- name: deploy webservices
  hosts: web
  become: yes
  roles:
    - webserver


- name: deploy zabbix
  hosts: zabbix
  become: yes
  vars:
    mysql_password: 'mysecretpass'
  roles:
    - zabbix-server

- name: deploy zabbix agent
  hosts:
    - elasticsearch_servers
    - kibana_servers
    - web
    - bastion
  become: yes
  roles:
    - zabbix-agent

